### ISSUE TITLE
Dorothy 0.0.7 release executable: Invalid drop percentage

### ISSUE THREAD

**Issue by daspers** [NadyaNayme/Dorothy#12]
The calculation of the drop rate is using the number of blue chests from GOHL instead of the correct blue chests count
![Screenshot 2022-04-05 001802](https://user-images.githubusercontent.com/26574054/161587765-7701b96f-4458-43ef-876d-37fe4f41f607.png)

The image above is using the configuration below
```
[drops]
akasha_coronation_rings=23
akasha_lineage_rings=4
akasha_gold_bars=0
pbhl_no_blue_boxes=70
pbhl_blue_boxes=12
pbhl_coronation_rings=9
pbhl_lineage_rings=3
pbhl_intricacy_rings=0
pbhl_gold_bars=0
gohl_no_blue_boxes=0
gohl_blue_boxes=16
gohl_coronation_rings=4
gohl_lineage_rings=0
gohl_intricacy_rings=0
gohl_trash=12
gohl_gold_bars=0
akasha_intricacy_rings=6
crystals_amount=0
ten_pulls_amount=0
single_pulls_amount=0
akasha_no_blue_boxes=1
akasha_blue_boxes=375
akasha_trash=342
```

**Comment by NadyaNayme** [comment]
I looked at this a bit last night and it wasn't immediately obvious where the wires were getting crossed. After a good night's rest I see exactly what the issue is. If you have 0 GOHL chests then Akasha will be screwed up if you have any PBHL chests. If you have any GOHL chests then both Akasha and PBHL are screwed up.

I'll see if I can push out a quick fix so that this works properly and I can turn my attention back over to the GUI rewrite.

**Comment by NadyaNayme** [comment]
I pushed out a release that _should_ fix this issue (I tested it and tested it in the known problematic cases and didn't encounter the issue again). Each tab calculates only its own percentages so wires shouldn't be crossed anymore. The fix wasn't very clean but I don't care to fix this "properly" since I'm rewriting it anyways.

https://github.com/NadyaNayme/Dorothy/releases/tag/0.0.8
